# Generated by Django 3.2 on 2023-03-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_achivement_achivementcat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achivement',
            new_name='Achievement',
        ),
        migrations.RenameModel(
            old_name='AchivementCat',
            new_name='AchievementCat',
        ),
        migrations.RenameField(
            model_name='achievementcat',
            old_name='achivement',
            new_name='achievement',
        ),
    ]
